name: Update Strava Stats

# This runs the job on a schedule (e.g., every 6 hours)
# and also allows you to run it manually from the "Actions" tab
on:
  schedule:
    - cron: '0 */6 * * *' # Runs at 0 minutes past the hour, every 6 hours
  workflow_dispatch: # Allows manual runs

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    # Give the script permission to write back to your repository
    permissions:
      contents: write
      
    steps:
      # 1. Check out your repository's code
      - name: Check out repo
        uses: actions/checkout@v4

      # 2. Set up Node.js (the environment for our script)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install the dependencies (node-fetch)
      - name: Install dependencies
        run: npm install

      # 4. Run your private backend script
      # This is where your secrets are safely injected
      - name: Fetch Strava Stats
        run: node fetch-stats.js
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_ATHLETE_ID: ${{ secrets.STRAVA_ATHLETE_ID }}

      # 5. Commit the new stats.json file back to your repository
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated Strava stats"
          file_pattern: stats.json